from __future__ import annotations

import pandas as pd
import pytest

from linkage import config as config_mod
from linkage import prior as prior_mod
from linkage.score import WORKED_EXAMPLE_ROWS, print_worked_example, worked_example


def test_worked_example_reproduces_spec_within_tolerance(capsys):
    rows = worked_example()
    for r in rows:
        assert abs(r["diff"]) <= 0.05, r
    total = sum(r["my_bits"] for r in rows)
    assert total == pytest.approx(5.845, abs=0.05)


def test_worked_example_cli_passes():
    assert print_worked_example() is True


def test_worked_example_covers_every_spec_row():
    # sanity: didn't drop a row when transcribing TECHNICAL_SPEC.md §4.3
    assert len(WORKED_EXAMPLE_ROWS) == 11


@pytest.fixture(scope="module")
def truth():
    t = pd.read_parquet("data/final/truth.parquet")
    return t[t["ingested"]]


def test_prior_matches_published_manifest_numbers(truth):
    # data/final/manifest.json and DATASET.md were generated by
    # linkage/generate/report.py's pair_stats, which linkage/prior.py mirrors.
    p = prior_mod.compute(truth)
    assert p["same_type"]["BURGLARY_RESIDENTIAL"] == pytest.approx(-15.083, abs=0.01)
    assert p["same_type"]["ATM_TAMPERING"] == pytest.approx(-12.16, abs=0.01)
    assert p["cross_type"] == pytest.approx(-16.931, abs=0.01)
    assert p["all_property"] == pytest.approx(-15.937, abs=0.01)


def test_config_alpha_matches_corpus_repeat_rate():
    cfg = config_mod.load()
    rr = cfg["corpus"]["repeat_rate"]
    a = config_mod.alpha(rr["value"], rr["reference_frequency"])
    assert a > 0
